Show progress bar when mp data.  New accent color.
gbielanski/GarbageApp pull request #15
Opened 2018-01-01 18:28 UTC by gbielanski

Please review

2018-01-02 23:39 UTC, miltomasz requested changes
Two refactorings needed. Please see comments. However I don't think this solution is good. It will work (I tested it) but it will keep showing progress bar even when we have finished request action but there's no data.

You may try just add:

binding.progressBar.setVisibility(View.VISIBLE);

in every onCreate() in ActivitySector[Green,Blue, Yellow].

Next, add binding.progressBar.setVisibility(View.GONE);

in bindDataToUI() method in every ActivitySector[Green,Blue, Yellow]. It should work with bindings framework. And it will show progress bar only when request is ongoing.

2018-01-02 23:39 UTC, miltomasz commented on app/src/main/java/pl/example/android/garbageapp/ui/ActivitySectorBlue.java
> +    private RecyclerView.AdapterDataObserver mDataObserver = new RecyclerView.AdapterDataObserver() {
Please declare this adapter as protected and move it to BaseActivitySector

2018-01-02 23:39 UTC, miltomasz commented on app/src/main/java/pl/example/android/garbageapp/ui/ActivitySectorBlue.java
> +        void checkEmpty() {
Define checkEmpty() as abstract method in BaseActivitySector. Next, override this method in each SectorActivity and use correct bindings.

2018-01-03 21:20 UTC, gbielanski commented
As this is MVP version, progress bar behavior is implemented in this way intentionally. I opened separated ticked in Trello to cover all cases when list can be empty.
I extracted function checkEmpty to BaseActivitySector. It was good idea and cleaned the code.

2018-01-03 23:47 UTC, miltomasz approved these changes

2018-01-04 08:24 UTC, merged