Use Stetho
gbielanski/GarbageApp pull request #16
Opened 2018-01-03 21:33 UTC by gbielanski

Please review

2018-01-03 23:50 UTC, miltomasz requested changes

2018-01-03 23:50 UTC, miltomasz commented on app/build.gradle
> +    compile 'com.facebook.stetho:stetho:1.4.1'
Please change it to 'debugCompile' as we don't need this in our release apk.

2018-01-04 10:54 UTC, gbielanski commented
Please review

2018-01-04 16:46 UTC, miltomasz approved these changes

2018-01-04 21:18 UTC, merged