reset alarm manager after reboot
gbielanski/GarbageApp pull request #17
Opened 2018-01-06 12:04 UTC by gbielanski

please review

2018-01-06 23:13 UTC, miltomasz requested changes
Just correct formatting and TAG.

2018-01-06 23:13 UTC, miltomasz commented on app/src/main/AndroidManifest.xml
> +    </application>
Format code above

2018-01-06 23:13 UTC, miltomasz commented on app/src/main/java/pl/example/android/garbageapp/AlarmReceiver.java
> +        Log.d("AlarmReceiver", "onReceive");
Create tag as final string constant (AlarmReceiver.class.getSimpleName();)

2018-01-07 15:43 UTC, gbielanski commented
Please review

2018-01-07 18:08 UTC, miltomasz approved these changes

2018-01-07 18:46 UTC, merged