Add job service syncing with Firebase every 12hrs
gbielanski/GarbageApp pull request #8
Opened 2017-11-14 22:27 UTC by miltomasz

Changes introduce job service triggering fetch action for Firebase twice a day. The frequency can be changed later on if needed.

2017-11-16 14:40 UTC, gbielanski requested changes

2017-11-16 14:40 UTC, gbielanski commented on app/src/main/java/pl/example/android/garbageapp/data/SectorTermRepository.java
> +        int futureWeather = mSectorTermDao.countAllFutureSectorTerms(today);
It is not a weather :)

2017-11-16 14:40 UTC, gbielanski commented on app/src/main/java/pl/example/android/garbageapp/data/network/SectorTermsNetworkDataSource.java
> +
NUM_DAYS should be greater. I think it should be 2 mounths (60 days) at least.

2017-11-16 14:40 UTC, gbielanski commented on app/src/main/java/pl/example/android/garbageapp/data/network/SectorTermsNetworkDataSource.java
> +        Job syncSunshineJob = dispatcher.newJobBuilder()
It is not Sunshine

2017-11-16 14:40 UTC, gbielanski commented on app/src/main/java/pl/example/android/garbageapp/data/SectorTermRepository.java
> +        return futureWeather < SectorTermsNetworkDataSource.NUM_DAYS;
This condition is wrong. Dao countAllFutureSectorTerms will return number of terms. We cannot compare it to number of days.

2017-11-19 19:15 UTC, miltomasz commented
Hi,

I removed isFetchNeeded method as discussed. Now the app will be fetching sector terms in two ways:
- at the startup of the app
- next every 12hrs (twice a day). This will be handled by job service.

The issue to think about is how to set up a retry mechanism when app fails to download data (especially at startup).

2017-11-19 20:52 UTC, gbielanski approved these changes
Changes approved.

2017-11-19 20:55 UTC, gbielanski commented
Let's leave discussion about sync fails and other special cases to consider in a separate topic.

2017-11-21 16:35 UTC, merged